repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy pytest_clab
        language: system
        types: [python]
        pass_filenames: false

      - id: unit-tests
        name: unit tests
        entry: uv run pytest
        language: system
        types: [python]
        pass_filenames: false
